---
apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  image:
    productVersion: 2.10.4
  clusterConfig:
    listenerClass: external-unstable
    loadExamples: false
    exposeConfig: false
    credentialsSecret: airflow-credentials
    dagsGitSync:
      - repo: https://github.com/stackabletech/demos/
        branch: spike/argocd-demo
        gitFolder: "demos/argo-cd/dags"
        depth: 2
    volumes:
      - name: minio-tls
        ephemeral:
          volumeClaimTemplate:
            metadata:
              annotations:
                secrets.stackable.tech/class: tls
                secrets.stackable.tech/scope: pod,node
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: "1"
              storageClassName: secrets.stackable.tech
    volumeMounts:
      - name: minio-tls
        mountPath: /stackable/minio-tls
  webservers:
    envOverrides: &envOverrides
      AIRFLOW_CONN_KUBERNETES_IN_CLUSTER: "kubernetes://?__extra__=%7B%22extra__kubernetes__in_cluster%22%3A+true%2C+%22extra__kubernetes__kube_config%22%3A+%22%22%2C+%22extra__kubernetes__kube_config_path%22%3A+%22%22%2C+%22extra__kubernetes__namespace%22%3A+%22%22%7D"
      # Via sealed secrets, just kept for reference here
      #AIRFLOW_CONN_MINIO: "aws://admin:adminadmin@/?endpoint_url=https%3A%2F%2Fminio.minio.svc.cluster.local%3A9000"
      AWS_CA_BUNDLE: "/stackable/minio-tls/ca.crt"
      AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
      AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: s3://demo/airflow-task-logs/
      AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: minio
    podOverrides: &podOverrides
      spec:
        containers:
          - name: airflow
            env:
              - name: AIRFLOW_CONN_MINIO
                valueFrom:
                  secretKeyRef:
                    name: airflow-minio-connection
                    key: airflow-minio-connection
    config:
      gracefulShutdownTimeout: 30s
      resources:
        cpu:
          min: 400m
          max: "1"
        memory:
          limit: 1Gi
    roleGroups:
      default:
        replicas: 1
  kubernetesExecutors:
    envOverrides: *envOverrides
    podOverrides:
      spec:
        containers:
          - name: base
            env:
              - name: AIRFLOW_CONN_MINIO
                valueFrom:
                  secretKeyRef:
                    name: airflow-minio-connection
                    key: airflow-minio-connection
  schedulers:
    envOverrides: *envOverrides
    podOverrides: *podOverrides
    config:
      gracefulShutdownTimeout: 30s
      resources:
        cpu:
          min: 400m
          max: "1"
        memory:
          limit: 1Gi
    roleGroups:
      default:
        replicas: 1
