apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-postgres
spec:
  project: airflow
  destination:
    server: https://kubernetes.default.svc
    namespace: stackable-airflow
  sources:
    - repoURL: "registry-1.docker.io/bitnamicharts"
      path: postgresql
      # helm inspect chart oci://registry-1.docker.io/bitnamicharts/postgresql
      targetRevision: 16.6.3 # 17.4.0
      chart: postgresql
      helm:
        # TODO this breaks naming as long as we use the airflow stack yaml which needs this svc name
        releaseName: postgresql-airflow
        valuesObject:
          commonLabels:
            stackable.tech/vendor: Stackable
          auth:
            database: airflow
            existingSecret: postgres-credentials
    - repoURL: https://github.com/stackabletech/demos.git
      # TODO: adapt to release-25.3
      targetRevision: "spike/argocd-demo"
      path: demos/argo-cd/manifests/airflow-postgres/
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
