---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stackable-operators
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - operator: commons
                - operator: listener
                - operator: secret
                - operator: airflow
                - operator: druid
                - operator: hbase
                - operator: hdfs
                - operator: hive
                - operator: kafka
                - operator: nifi
                - operator: opa
                - operator: spark-k8s
                - operator: superset
                - operator: trino
                - operator: zookeeper
          - list:
              elements:
                - cluster: demo
                  server: https://kubernetes.default.svc
                  targetRevision: "25.3.0"
                  repoUrl: https://repo.stackable.tech/repository/helm-stable/
                # - cluster: development
                #   server: https://kubernetes-development.default.svc
                #   targetRevision: "0.0.0-dev"
                #   repoUrl: https://repo.stackable.tech/repository/helm-dev/
                # - cluster: staging
                #   server: https://kubernetes-staging.default.svc
                #   targetRevision: "25.3.0"
                #   repoUrl: https://repo.stackable.tech/repository/helm-stable/
                # - cluster: production
                #   server: https://kubernetes-production.default.svc
                #   targetRevision: "24.11.1"
                #   repoUrl: https://repo.stackable.tech/repository/helm-stable/
  # {% raw %}
  template:
    metadata:
      name: "{{ operator }}-operator"
    spec:
      project: stackable-operators
      ignoreDifferences:
        # mitigating: https://github.com/stackabletech/hdfs-operator/issues/626
        - group: "apiextensions.k8s.io"
          kind: "CustomResourceDefinition"
          jqPathExpressions:
            - .spec.names.categories | select(. == [])
            - .spec.names.shortNames | select(. == [])
            - .spec.versions[].additionalPrinterColumns | select(. == [])
      source:
        repoURL: "{{ repoUrl }}"
        targetRevision: "{{ targetRevision }}"
        chart: "{{ operator }}-operator"
        helm:
          releaseName: "{{ operator }}-operator"

      destination:
        server: "{{ server }}"
        namespace: stackable-operators
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        automated:
          selfHeal: true
          prune: true
  # {% endraw %}
