---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: default
  sources:
    - repoURL: "registry-1.docker.io/bitnamicharts"
      path: sealed-secrets
      targetRevision: 2.5.16 # 0.30.0
      chart: sealed-secrets
      helm:
        releaseName: sealed-secrets-controller
        valuesObject:
          secretName: sealed-secrets-key
    # TODO: This should be parameterized with customGitUrl and customGitBranch
    # Currently these parameters are defined in the demo-v2.yaml and are
    # not picked up in the stack - What to do?
    - repoURL: https://github.com/stackabletech/demos/
      targetRevision: spike/argocd-demo
      path: stacks/argo-cd-git-ops/secrets/
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
