---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: default
  sources:
    - repoURL: "registry-1.docker.io/bitnamicharts"
      path: sealed-secrets
      targetRevision: 2.5.16 # 0.30.0
      chart: sealed-secrets
      helm:
        releaseName: sealed-secrets-controller
        valuesObject:
          secretName: sealed-secrets-key
    - repoURL: "{{ customGitUrl }}"
      targetRevision: "{{ customGitBranch }}"
      path: stacks/argo-cd-git-ops/secrets/
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
