apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  project: minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  source:
    repoURL: https://github.com/stackabletech/demos.git
    targetRevision: "{{ demoReleaseVersion }}"
    path: stacks/argo-cd/manifests/minio/
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
