---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: default
  sources:
    - repoURL: "registry-1.docker.io/bitnamicharts"
      path: sealed-secrets
      targetRevision: 2.5.9 # 0.29.0
      chart: sealed-secrets
      helm:
        releaseName: sealed-secrets-controller
        valuesObject:
          secretName: sealed-secrets-key
    - repoURL: https://github.com/stackabletech/demos.git
      # TODO: adapt to release-25.3
      targetRevision: "spike/argocd-demo"
      path: stacks/argo-cd/secrets/
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
