---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secret-operator
spec:
  generators:
    - list:
        elements:
          - cluster: development
            url: https://kubernetes.default.svc
            helmChartRevision: 25.3.0
            targetRevision: HEAD
  template:
    metadata:
      name: secret-operator
    spec:
      project: stackable-operators
      ignoreDifferences:
        # mitigating: https://github.com/stackabletech/hdfs-operator/issues/626
        - group: "apiextensions.k8s.io"
          kind: "CustomResourceDefinition"
          jqPathExpressions:
            - .spec.names.categories | select(. == [])
            - .spec.names.shortNames | select(. == [])
            - .spec.versions[].additionalPrinterColumns | select(. == [])
      source:
        repoURL: https://repo.stackable.tech/repository/helm-stable/
        targetRevision: 25.3.0
        chart: secret-operator
        helm:
          releaseName: secret-operator
      destination:
        server: "{{url}}"
        namespace: stackable-operators
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        automated:
          selfHeal: true
          prune: true
